### ISSUE TITLE
errores

### ISSUE THREAD

**Issue by FernandoWsky** [aruppi/Aruppi#11]
**Describe the bug**
El botón de la foto adelanta 1.18mins cuando los opening el 99% duran 1.30mins.

Cuando estas en medio de un capítulo digamos que un poco más que la mitad y le das en regresar para ver algo que no leíste la app 

se traba por completo(Esto solo sucede cuando estás viendo el anime desde el inicio por ende si lo van a revisar tendra que hacerlo cuando esté viendo un capítulo desde 0).

**Comment by Jeluchu** [comment]
¡Muchas gracias por el reporte del error @FernandoWsky!
En teoría se tenía puesto que el botón de "Saltar Opening" fuera de 1 minuto 30 segundos, por alguna razón que desconocemos es probable que se haya cambiado la duración del salto de ese botón. Lo revisamos para poderlo corregir en estos días y lanzar una nueva versión incluyendo esta corrección.

Desde este hilo podrás comprobar el estado actual de la corrección, cuándo tengamos corregido el problema con la nueva release te avisaremos por esta issue.

**Comment by Jeluchu** [comment]
Se ha cambiado el tiempo de 1 minuto y 18 segundos (78.000 milisegundos) a 1 minuto y 30 segundos (90.000 milisegundos), hemos incluido este cambio para que sea lanzado en la próxima versión 2.2.1 que llegará en los próximos días @FernandoWsky

Cerramos esta incidencia, si se vuelve a repetir en la versión 2.2.1 cuándo se distribuya, no dudes en reabrirla indicando el problema.

**Comment by FernandoWsky** [comment]
gracias y disculpen la molestia. 😳
