### ISSUE TITLE
Marcado y desmarcado de todos los episodios a la vez

### ISSUE THREAD

**Issue by Jeluchu** [aruppi/Aruppi#14]
Incluir dentro del listado de capítulos que se pueda incluir un botón para marcar y desmarcar todos los capítulos en una sola vez

**Comment by Fenixzone1313** [comment]
Me parece una excelente opción ya que si te das cuenta en finalizado es un fastidio hacerlo más si es una serie larga :|

**Comment by Jeluchu** [comment]
@Fenixzone1313 se está tomando en cuenta para introducir esta característica en la próxima actualización, por aquí iré cambiando el estado en caso de que se incluya 😄

**Comment by Jeluchu** [comment]
¡Buenas noticias @Fenixzone1313!
Esta característica ya está desarrollada, y esperamos que se pueda disfrutar en la próxima actualización (v2.3.0) de Aruppi, por el momento cerramos esta feature puesto que ya se ha completado el desarrollo de esta funcionalidad.
