### ISSUE TITLE
Error de hace mucho con la pausa

### ISSUE THREAD

**Issue by FernandoWsky** [aruppi/Aruppi#17]
**Bueno ya hace mucho tiempo si no es que desde siempre, El error esta en que la app en distintas situaciones se pausa y/o pone en pantalla negra y tienes que salir y volver a entrar cosa molesta, obviamente si se quiere mejorar la experiencia de los usuarios esto no creo que sea debido a los servidores puestos que solo sucede con el 2do plano y botón de retroceder y aveces con salta OP**

**cómo reproducir**
 el bug se da por muchas situaciones las cuales son cuando aruppi en 2do plano lo traba cuando intentas volver a entrar, cuando ya llevas viendo más de medio capitulo y retrocedes, cuando usas el de saltar opening en la misma situación ( más de la mitad del animé) y cuando aveces de pronto le da por pausarce solo. (No entres al cap y vallas a más de la mitad y des retroceder): ve a un capítulo y velo del 1 al 18 y dale retroceder o saltar op o sacar 2do plano y pam

Importantes: Ya reporte varias veces y me dieron explicaciones que no tienen sentido como el de que los servidores tienen tiempo límite, lo cual no tiene sentido puesto que son Anime FLV y no esté no tiene esta falla, y solo sucede con el hecho de que retrocedas o des saltar op.

Probado: Ya lo probé con 4 teléfonos, huawei Y7, Samsung galaxy, Hisense y ahora un Xiaomi redmi 9 global.

Espero se solucione porque siempre miro un capítulo con miedo de no perderme algo importante porque tengo que salir y volver a entrar y dar "continuar"

**Comment by Jeluchu** [comment]
@FernandoWsky como bien dices y como muchas veces te habremos dicho, y aunque tú digas que no es por los servidores, te volveremos a explicar de nuevo el porqué sucede esto.

Cuándo tú pulsas en un capítulo para ver los diversos servidores que hay disponibles, y pulsas en un servidor concreto (hablo ahora específicamente de aquellos que se abren con el reproductor interno de Aruppi), se realizan diversas transformaciones de los enlaces de los servidores de las páginas de Animeflv, JKAnime, TioAnime, MonosChinos, etc para poder obtener el enlace con el vídeo.

Ese enlace "final" tiene una especie de token, la cuál tiene una validación concreta, además de que en muchos de ellos si varías incluso la IP o cambias tu conexión de red de Datos a Wi-fi (o viceversa) también puede afectar. Por lo que si tu estás en segundo plano y estas un rato dejando el capítulo en segundo plano, al regresar de nuevo a la app, el reproductor va a intentar recargar de nuevo ese enlace de ese vídeo en concreto, pero no va a poder porque ha caducado, por lo que deberás realizar el mismo proceso de antes, pulsar el capítulo y darle a un servidor.

Y ahora te voy a responder a lo que dices de: "explicaciones que no tienen sentido". Cuándo seguramente tú te metes en Animeflv te estás metiendo desde un navegador web, por lo que es totalmente diferente que estando desde una aplicación totalmente externa a ellos. Además de que ten en cuenta que dichas webs son las que controlan esos servidores, por lo que a ellos nunca les va a suceder, pero en cambio cuándo terceros intentan acceder a esos enlaces tienen diversas complicaciones y expiraciones, esto lo hemos intentado revisar muchas veces pero el resultado siempre ha sido el mismo, y sino que me corrijan @Darkangeel-hd o @guillermoriv
