### ISSUE TITLE
El servidor de streamiun No funciona y no puedo me deja otro server

### ISSUE THREAD

**Issue by Dannyuchi** [aruppi/Aruppi#18]
**Describe the bug**
Cuando intento ver cualquier anime en streamiun no me deja y no funcionan ningun otro servidor 

**To Reproduce**
1. Go to 'any anime'
2. Click on 'server streamiun'

**Expected behavior** 
Que entre normalmente

**Screenshots**
![Screenshot_20210905-175956](https://user-images.githubusercontent.com/90158852/132142788-58501572-441e-4cc4-850f-2eb32c7edee3.png)
)

**Smartphone (please complete the following information):**
 - Device: [e.g. Realme]
 - Version OS: [e.g. Android 9]

**Aruppi (please complete the following information):**
 - Version: [e.g. v2.2.5]
 - Target: [e.g. Pro]

**Additional context**

**Comment by Jeluchu** [comment]
@Dannyuchi este no es un problema de Aruppi, te recordamos que Aruppi no posee ni almacena el contenido en nuestros servidores la reproducción se obtiene de enlaces de terceros los cuáles no tenemos el control. Por lo que si eliminan el vídeo del enlace que obtenemos de Animeflv, JKAnime, MonosChinos o TioAnime, nosotros no podemos hacer nada, ya que obtenemos los datos de estas páginas y no tenemos ningún control sobre ellas.
