### ISSUE TITLE
Posibilidad de Descargar Episodios en Aruppi Pro

### ISSUE THREAD

**Issue by ToastcodeDev** [aruppi/Aruppi#3]
Buenas Jéluchu, habías pensado en la implementación de algún sistema de descargas?

He estado investigando por acá en GitHub y he visto un proyecto de código abierto llamado [UKIKU](https://github.com/jordyamc/UKIKU) el cual tiene esta función y además la aplicación fue adaptada a kotlin hace unos años así que tal vez puedas implementar un sistema así (claramente si es posible de lo contrario puedes descartar esta idea).

**Comment by Jeluchu** [comment]
¡Hola @ToastcodeDev!

La verdad es que sobre el tema del **"Sistema de descargas"**, mucha gente lo ha sugerido, y hay un gran dilema sobre dicha característica, además de que en parte Aruppi también quiere ser un apoyo a la industria del anime, de ahí la sección del **"¡Apoya al Anime legal!"** (en la cuál estamos incluyendo contenido para próximamente mostrarlo).

En estos momentos como ya sabrás, en nuestro servidor, no tenemos alojado ningún tipo de vídeo, puesto que es obtenido de las páginas de terceros _(actualmente Animeflv y JKAnime, las cuales estamos en vía de ampliar a más fuentes)_, como tal no veo ético el incluir la función de **"Descarga de episodios"** cuándo puedes verlo con la conexión a internet, y que actualmente todo el mundo está casi las 24 horas conectado.

Por el momento, lo dejo como una sugerencia, aunque actualmente o en un futuro cercano, mi intención actualmente es centrarme en seguir introduciendo otro tipo de características, mejoras e incluir más contenido a la aplicación, todo esto ira llegando a lo largo del año y como siempre, se anunciará por redes públicamente, o por privado con antelación para aquellas personas que donan, que son los que están al tanto de las cosas antes que nadie y pueden ver la preview de la versión de desarrollo.

De todos modos, si tienes cualquier otra sugerencia, mejora o problema, te invito a crear otra issue y será revisada. Además como no, agradecerte que uses la aplicación y que sugieras nuevos cambios en ella, es todo un placer de verdad.

Arigato, Matta ne! 🎏

**Comment by ToastcodeDev** [comment]
¡Buena respuesta!
