### ISSUE TITLE
Selección de un servidor como predeterminado.

### ISSUE THREAD

**Issue by Heavybass4** [aruppi/Aruppi#6]
La opción de seleccionar algun servidor como predeterminado para saltar la opción de seleccionar un servidor cada vez que se reproduce un episodio. En caso de no estar disponible, que aparezca la opción de seleccionar otro disponible.

**Comment by Jeluchu** [comment]
¡Muchas gracias por la sugerencia @Heavybass4!
Se revisará dicha función para incluirla dentro de la futura actualización, iremos comentando el estado de esta nueva característica dentro de este mismo hilo

**Comment by Fenixzone1313** [comment]
O que también pueda elegir automáticamente osea el más óptimo y que también puedas cambiar de capítulo automáticamente como si fuera una foto de la galería bueno creo yo que sería mejor ya que normanelte es un poco fastidioso tener que salir de un cap para entrar al otro

**Comment by Jeluchu** [comment]
@Fenixzone1313 nosotros no podemos saber cuál es el más óptimo puesto que no tenemos el control de esos servidores, ya que obtenemos los datos de páginas de terceros como Animeflv, JKAnime, MonosChinos o TioAnime, pero si que podemos incluir que el usuario pueda seleccionar un servidor por defecto, y que en caso de no estar ese servidor en la lista del capítulo, pues te muestre el diálogo del listado de servidores.

**Comment by Jeluchu** [comment]
¡Buenas noticias @Fenixzone1313 y @Heavybass4!
Esta característica ya está desarrollada, y esperamos que se pueda disfrutar en la próxima actualización (v2.3.0) de Aruppi, por el momento cerramos esta feature puesto que ya se ha completado el desarrollo de esta funcionalidad.
